index:
    path: /
    controller: App\Controller\DefaultController::index

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

# PARA AREAS nelmio_api_doc.yml
#app.swagger_ui:
#    path: /api/doc/{area}
#    methods: GET
#    defaults: { _controller: nelmio_api_doc.controller.swagger_ui, area: default }    


#api2:
#    resource: "App/Controller/Api2Controller"
#    type: rest
#    prefix: /api2/c    